version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/internal/static"
    schedule:
      interval: "daily"
