package plot

import "runtime/metrics"

var _ = register(description{
	name: "gc-cycles",
	tags: []tag{tagGC},
	metrics: []string{
		"/gc/cycles/automatic:gc-cycles",
		"/gc/cycles/forced:gc-cycles",
		"/gc/cycles/total:gc-cycles",
	},
	layout: Scatter{
		Name:  "TODO(set later)",
		Title: "Completed GC Cycles",
		Type:  "bar",
		Layout: ScatterLayout{
			BarMode: "stack",
			Yaxis: ScatterYAxis{
				Title: "cycles",
			},
		},
		Subplots: []Subplot{
			{
				Name:    "automatic",
				Unitfmt: "%{y}",
				Type:    "bar",
			},
			{
				Name:    "forced",
				Unitfmt: "%{y}",
				Type:    "bar",
			},
		},
		InfoText: `Number of completed GC cycles, either forced of generated by the Go runtime.`,
	},
	make: func(idx ...int) metricsGetter {
		return &gcCycles{
			idxAutomatic: idx[0],
			idxForced:    idx[1],
			idxTotal:     idx[2],
		}
	},
})

type gcCycles struct {
	idxAutomatic int
	idxForced    int
	idxTotal     int

	lastAuto, lastForced, lastTotal uint64
}

func (p *gcCycles) values(samples []metrics.Sample) any {
	total := samples[p.idxTotal].Value.Uint64()
	auto := samples[p.idxAutomatic].Value.Uint64()
	forced := samples[p.idxForced].Value.Uint64()

	if p.lastTotal == 0 {
		p.lastTotal = total
		p.lastForced = forced
		p.lastAuto = auto
		return []uint64{0, 0}
	}

	ret := []uint64{
		auto - p.lastAuto,
		forced - p.lastForced,
	}

	p.lastForced = forced
	p.lastAuto = auto

	return ret
}
